### ISSUE TITLE
Question: are what we can natural-transformations actually morphisms

### ISSUE THREAD

**Issue by andygill** [ku-fpg/blackboard#16]
We have a package called natural-transformation. But we do not require the Functor constraint. So they are not technically natural transformations. Are they actually a form of morphisms, or Homomorphism.

Lets check we've got the terminology correct.

**Comment by roboguy13** [comment]
Based on the [description of the invariant package](http://hackage.haskell.org/package/invariant-0.3/docs/Data-Functor-Invariant.html), it sounds like anything with a kind `* -> *` would at least be an invariant/exponential functor (even if it isn't necessarily a capital-F Haskell `Functor`). So, I suspect we are safe calling these natural transformations.

**Comment by andygill** [comment]
Good to know. I'll close the ticket.
