### ISSUE TITLE
Update Hackage versions of packages for GHC 7.10

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/blackboard#5]
Now that GHC 7.10 is out, we should reupload several `ku-fpg` packages to Hackage so that they can be used with GHC 7.10. Here are the ones that I've updated recently, and are ready to be uploaded now:
- [x] `data-reify`
- [x] `html-kure`
- [x] `hood`
- [x] `marked-pretty`
- [x] `sized-types`

I could take care of this, but I'll need to be added to the maintainer groups for each package on Hackage.

These packages need to undergo some work before they can be uploaded:
- [ ] `kansas-comet`
- [ ] `blank-canvas`
- [ ] `yampa-canvas`
- [ ] `sunroof-compiler`
- [ ] `sunroof-server`
- [ ] `sunroof-examples`

**Comment by andygill** [comment]
Sounds good. Come by my office tomorrow, and we'll update the maintainer live.

**Comment by RyanGlScott** [comment]
This has been done.
